### ISSUE TITLE
Issues in cmsweb-ping

### ISSUE THREAD

**Issue by muhammadimranfarooqi** [dmwm/cmsweb-exporters#2]
Hi,

There seems to be issue in `cmsweb-ping`. In case of DBS query, if I use wrong query it still results 200 code which should not be the case. 

cmsweb-ping --url=http://localhost:8252/dbs/xxx/global/DBSReader/ --authz=/etc/hmac/hmac -verbose 0
200 OK

Please investigate. Thanks

**Comment by vkuznet** [comment]
@muhammadimranfarooqi there is no error in cmsweb-ping itself, see it using verbose option:
```
cmsweb-ping --url=http://localhost:8252/dbs/prod/global/DBSReader/datasets?dataset=/ZMM*/*/* --authz=/etc/hmac/hmac -verbose 1
request:  GET /dbs/prod/global/DBSReader/datasets?dataset=/ZMM*/*/* HTTP/1.1
Host: localhost:8252
User-Agent: Go-http-client/1.1
Accept: */*
Cms-Auth-Status: OK
Cms-Authn-Hmac: 0af6ab4752bf1591491b355004f941ce0bf5bff5
Cms-Authn-Login: ping-monitor
Cms-Authn-Method: PingMonitor
Cms-Authn-Name: Ping Monitor
Accept-Encoding: gzip


response: HTTP/1.1 200 OK
Content-Type: text/html;charset=utf-8
Date: Mon, 23 Aug 2021 14:25:38 GMT
Etag: "82bdf691e91df1d5bc8e13c85420ef32"
Server: CherryPy/17.4.0
Vary: Accept-Encoding

<html><head><link rel="stylesheet" type="text/css" href="/controllers/css/reset/style.css"/></head><body><h1>Welcome to the DMWM web framework</h1><hr style="width:100%;border-top: 1px dotted #CCCCCC;" /><table>
<tr><th align="left"><h3>Service</h3></th>
<th align="left"><h3>Description</h3></th></tr>
<tr><td><p><a href="int/global/DBSReader">int/global/DBSReader</a></p></td>
<td><p>
    DBS3 Server API Documentation
    </p></td></tr>
</table><br /></body></html>
200 OK
```
Its output returns 200 OK since the DBS server intercept request and return some output. In this case DBS server itself returns that there is no such url, and client should use a different one. It is an issue of DBS server which should not return 200 OK in this case and should use 301 or similar code.

@yuyiguo it is issue with DBS server which should not return 200 OK when wrong URL is provided. Since DBS server issue a redirect it should use a different HTTP code.

@muhammadimranfarooqi  What you should do is to properly parse the output to see if it makes sense. If you'll run
```
cmsweb-ping --url=http://localhost:8252/dbs/int/global/DBSReader/datasets?dataset=/ZMM*/*/* --authz=/etc/hmac/hmac -verbose 1
...
[....
{"dataset": "/ZMM_14TeV_TuneCUETP8M1_Pythia8/PhaseIIFall17D-L1TPU140_93X_upgrade2023_realistic_v5-v1/GEN-SIM-DIGI-RAW"}
]
200 OK
```
you'll get 200 OK and correct output. Therefore, I suggest that you adjust dbs manifest file to properly grep `dataset` output in this case.

**Comment by yuyiguo** [comment]
Hi Valentin,
`http://localhost:8252/dbs/int/global/DBSReader/datasets?... `  was a correct url if you were testing on the int k8s pods.  
If I do `https://cmsweb.cern.ch/dbs/int/global/DBSWriter/` , I got  "default backend - 404". Because cmsweb should use "prod" instead of "int". 
To answer your question
_One more thing, when you wrong "Obviously DBS servers were down for more than
one hours" how do you know that it was down?_ 

I knew it because in the alert email, it said below and I got the message more an hour ago.
_"description = k8s-prod has been down for more than 5m"_
In addition to that message, the timber plots also showed the same.

I don't think one time pin failed is enough  to say the system is dead. I don't know how often you pin. I would say if you pinned for 5 minutes and 50% or more were failed, then a restart is needed.

Hi Imran,
on k8s prod , we have below urls that need to be tested for `cmsweb-pin`
```
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/
https://cmsweb.cern.ch/dbs/prod/global/DBSWriter/
https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader/
https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter/
```
You can use below API to pin each of these instances
datatiers?data_tier_name=DIGI-RECO
This API also works with the k8s int dbs:
```
 https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/
https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter/
https://cmsweb-testbed.cern.ch/dbs/int/phys03/DBSReader/
https://cmsweb-testbed.cern.ch/dbs/int/phys03/DBSWriter/
```

All  the API will have `"data_tier_name": "DIGI-RECO"` in the output if you want to check the output. 

Let me know if you have any problem with these APIs.

Thanks,
Yuyi

**Comment by muhammadimranfarooqi** [comment]
Hi @yuyiguo

I have setup now the URL `url=http://localhost:8252/dbs/prod/global/DBSReader/` as you can see here. 

https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/services/dbs-global-r.yaml#L109

Previously, it was setup like this below command which did not trigger the restart.  

`- cmsweb-ping --url=http://localhost:8252/dbs/prod/global/DBSReader/datasets?dataset=/ZMM*/*/* --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"`

Infact with previous command livenessprobe was not failing. Now should be fine. 

Do you want to increase no of pods from 8 to 10 in case of high load and also the max ram?

**Comment by vkuznet** [comment]
@yuyiguo , I think you're missing the point. Let's iterate:
- if we use `http://localhost:8252/dbs/prod/global/DBSReader/` URL when running on int instance we get 200 OK with the following message:
```
<html><head><link rel="stylesheet" type="text/css" href="/controllers/css/reset/style.css"/></head><body><h1>Welcome to the DMWM web framework</h1><hr style="width:100%;border-top: 1px dotted #CCCCCC;" /><table>
<tr><th align="left"><h3>Service</h3></th>
<th align="left"><h3>Description</h3></th></tr>
<tr><td><p><a href="int/global/DBSReader">int/global/DBSReader</a></p></td>
<td><p>
    DBS3 Server API Documentation
    </p></td></tr>
</table><br /></body></html>
```
It means that HTTP code is 200 while the output says that we use incorrect URL. In this case, I expect DBS server to return 301 HTTP code instead of 200 OK

- If we use correct URL `http://localhost:8252/dbs/int/global/DBSReader/` on int instance (k8s setup) then we get main page, which is correct. But (!!!) it does not test DBS behavior, it only test the Python part of DBS server. In other words, the return output says NOTHING about DB connections. Therefore, if DBS experience DB issue this url will be fine but DB queries will fail. In other words, DBS will have DB issue while the probe will be fine. That's why I suggest to use actual API to test to DBS DB status. The API can be anything which DBS use to query the ORACLE.

Now regarding metrics. Again, here you **trust** the message which **we** setup in AM. What you should do is evaluate the metric conditions and decide if it is appropriate to define that DBS is having a problem. The AM metrics are setup by Prometheus which runs them at certain interval (defined in Prometheus configuration file). So far this interval is 5 seconds. What you get is that AM reports that during 5 seconds the metric `avg_open_fds < 1` is true, where `avg_open_fds` is defined as `avg_over_time(dbs_global_exporter_process_open_fds[5m])` (a average function which takes exporter process_open_fds metrics for last 5 min). Does it indication of DBS having issue? It is something that **YOU** should answer.

Now about cmsweb-ping. Its interval is defined in k8s manifest file, see https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/services/dbs-global-r.yaml#L111 and so far is defined to 10 seconds. The k8s will run it and if the command above will fail (cmsweb-ping will return not 200 code) it will restart the pod. Here again, you should consider if this condition is appropriate. So far we don't have **fine-granularity** like prove 10 times and then restart, since it is not in our hands. Instead, we need to have a tool which will do that. For instance, we can run cmsweb-ping 10 times with some interval in between and collect results, if such results will always fail we may declare that it is server failure. You are welcome to write such script and put the entire logic to shell script which can use cmsweb-ping tool. Our goal here is to help **developers (you)** with tools to define the logic. But we are not in charge of defining this logic for you. So far we use simple approach, and if you disagree with it please provide a tool which will do a full logic.

**Comment by yuyiguo** [comment]
Hi @muhammadimranfarooqi ,

Ar Valentin pointed in his message that the main page/url is not enough to indicate that DBS server is health or not. Please use the datatires API in  https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/services/dbs-global-r.yaml#L109.
I did not get why the dataset API you used previous did not trigger the restarted? What did it return when the server was dead?
 I would be nice to increase the max pods to 10 with high load.

Hi @vkuznet 

For all the PRODs, what you setup for in the AM is reasonable. However, for the INTs that has low access rates, it seems not that reasonable, but it does not matter because they are ints.

For the cmsweb-ping, what you put in is not reasonable to  me. It should not restart the server just because one ping is failed. What you described for the improvement seems much better.

**Comment by vkuznet** [comment]
@yuyiguo I spent this morning and wrote first version of [PodManager service](https://github.com/vkuznet/PodManager). It will rely on AlertManager (alerts) and can restart the pod. Therefore, it will be independent from service state, and if alert is fired, then PodManager can catch it and perform some action over the service pod, e.g. restart it. We'll test it and then apply to some services. DBS and CRABServer are primary candidates since they fail in a similar fashion, when number of fds is high. But new service will not be limited to single alert, it can use **ANY** alert we define in Prometheus to restart the service. Therefore, it will be up to dev-team (you) to define which alerts to use for this action.
